# Introducción a tensores

### ¿Qué son los Tensores?

Los tensores son una estructura de datos especializada que es muy similar a los arreglos (*arrays*) y las matrices. En frameworks como **PyTorch y TensorFlow**, utilizamos los tensores para codificar las entradas y salidas de un modelo, así como sus parámetros.

Los tensores son similares a los `ndarrays` de NumPy, con la principal diferencia de que pueden ejecutarse en GPUs u otro hardware especializado para acelerar drásticamente el cálculo computacional. Si estás familiarizado con los `ndarrays`, te sentirás como en casa con las APIs de tensores de estas bibliotecas.

In [ ]:
import tensorflow as tf
import numpy as np
import torch

Tensors are multi-dimensional arrays with a uniform type (called a `dtype`).  You can see all supported `dtypes` at `tf.dtypes`.

If you're familiar with [NumPy](https://numpy.org/devdocs/user/quickstart.html), tensors are (kind of) like `np.arrays`.

All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.


## Conceptos básicos

Algunos tensores básico pueden ser creados:

### Escalares (Tensores de Rango 0)

A continuación, presentamos un tensor **escalar** o de **rango 0**. Un escalar contiene un único valor numérico y carece de "ejes" (o dimensiones).

In [ ]:
# tensorflow
# int32 tensor por defecto
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# pytorch
# int64 tensor por defecto (en la mayoría de los sistemas)
rank_0_tensor = torch.tensor(4)
print(rank_0_tensor)

tensor(4)


### Vectores (Tensores de Rango 1)

Un **vector** o tensor de **rango 1** es como una lista de valores. Un vector tiene un único eje (o dimensión):

In [ ]:
# tensorflow
# tipo flotante
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [ ]:
# pytorch
# tipo flotante (float32 por defecto)
rank_1_tensor = torch.tensor([2.0, 3.0, 4.0])
print(rank_1_tensor)

tensor([2., 3., 4.])


### Matrices (Tensores de Rango 2)

Una **matriz** o tensor de **rango 2** tiene dos ejes (o dimensiones):

In [ ]:
# tensorflow
# es posible asignar el tipo de dato desde el inicio
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [ ]:
# pytorch
# es posible asignar el tipo de dato desde el inicio
rank_2_tensor = torch.tensor([[1, 2],
                              [3, 4],
                              [5, 6]], dtype=torch.float16)
print(rank_2_tensor)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float16)


<table>
<tr>
  <th>Un Escalar, shape: <code>[]</code></th>
  <th>Un vector, shape: <code>[3]</code></th>
  <th>Una Matriz, shape: <code>[3, 2]</code></th>
</tr>
<tr>
  <td>
   <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/scalar.png?raw=1" alt="A scalar, the number 4" />
  </td>

  <td>
   <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/vector.png?raw=1" alt="The line with 3 sections, each one containing a number."/>
  </td>
  <td>
   <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/matrix.png?raw=1" alt="A 3x2 grid, with each cell containing a number.">
  </td>
</tr>
</table>


### Tensores de Rango 3 (o más ejes)

Los tensores pueden tener más ejes; aquí tienes un ejemplo de un tensor con tres ejes:

In [ ]:
# Tensorflow
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
# PyTorch
rank_3_tensor = torch.tensor([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])


Existen muchas formas de visualizar un tensor con más de dos ejes.

<table>
<tr>
  <th colspan=3>Un tensor de 3 dimensiones, shape: <code>[3, 2, 5]</code></th>
<tr>
<tr>
  <td>
   <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/3-axis_numpy.png?raw=1"/>
  </td>
  <td>
   <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/3-axis_front.png?raw=1"/>
  </td>

  <td>
   <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/3-axis_block.png?raw=1"/>
  </td>
</tr>

</table>

Puedes convertir un tensor a un arreglo de NumPy (*NumPy array*) utilizando la función `np.array` o mediante el método `.numpy()` del propio tensor (disponible en ambos frameworks):

In [ ]:
np.asarray(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [ ]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

### Tipos de Datos y Formas Especiales

Los tensores suelen contener números de punto flotante (*floats*) y enteros (*ints*), pero también pueden almacenar otros tipos de datos, tales como:

* Números complejos.
* Cadenas de texto o *strings* (característica nativa en TensorFlow, aunque no soportada directamente en PyTorch).

Por diseño, las clases base (`tf.Tensor` y `torch.Tensor`) exigen que los tensores sean "rectangulares" —es decir, a lo largo de cada eje, todas las listas de elementos deben tener exactamente el mismo tamaño—. Sin embargo, existen tipos especializados de tensores que permiten manejar estructuras diferentes:

* **Tensores irregulares o dentados:** Útiles cuando los datos no tienen un tamaño uniforme (conocidos como *Ragged Tensors* en TensorFlow y *Nested Tensors* en PyTorch).
* **Tensores dispersos:** Estructuras optimizadas para almacenar datos donde la gran mayoría de los valores son cero (*Sparse Tensors* en ambos frameworks).

### Atributos y Geometría de los Tensores

Los atributos de un tensor describen su forma (*shape*), su tipo de dato (*datatype* o *dtype*) y el dispositivo (*device*) en el que están almacenados (por ejemplo, en la memoria de la CPU o en una GPU).

Hablando específicamente de la estructura, los tensores tienen dimensiones definidas. Aquí tienes un poco de vocabulario esencial para entender su geometría:

*   **Forma (*Shape*)**: La longitud (número de elementos) de cada uno de los ejes de un tensor.
*   **Rango (*Rank*)**: El número de ejes del tensor. Un escalar tiene rango 0, un vector tiene rango 1 y una matriz tiene rango 2.
*   **Eje (*Axis*) o Dimensión (*Dimension*)**: Una dimensión en particular de un tensor.
*   **Tamaño (*Size*)**: El número total de elementos contenidos en el tensor (calculado como el producto de los elementos de su forma o *shape*).

> **Nota:** Aunque es muy común escuchar referencias a un "tensor de dos dimensiones", en el contexto del aprendizaje automático, un tensor de rango 2 no suele describir un espacio geométrico 2D, sino más bien una estructura de datos (como una tabla de filas y columnas).

Los tensores en ambos frameworks (junto con sus objetos de forma, como `tf.TensorShape` en TensorFlow y `torch.Size` en PyTorch) proporcionan propiedades muy prácticas para acceder a todos estos valores desde el código:

In [ ]:
# tensorflow
rank_4_tensor_zeros_tf = tf.zeros(shape=[3, 2, 4, 5])
# pytorch
rank_4_tensor_ones_pt = torch.ones(size=[3, 2, 4, 5])

<table>
<tr>
  <th colspan=2>Un tensor de rango 4, shape: <code>[3, 2, 4, 5]</code></th>
</tr>
<tr>
  <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/shape.png?raw=1" alt="A tensor shape is like a vector.">
    <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/4-axis_block.png?raw=1" alt="A 4-axis tensor">
  </td>
  </tr>
</table>


In [ ]:
# TensorFlow
print("Tipo de cada elemento:", rank_4_tensor_zeros_tf.dtype)
print("Número de ejes:", rank_4_tensor_zeros_tf.ndim)
print("Forma del tensor:", rank_4_tensor_zeros_tf.shape)
print("Elementos en el eje 0 del tensor:", rank_4_tensor_zeros_tf.shape[0])
print("Elementos en el último eje del tensor:", rank_4_tensor_zeros_tf.shape[-1])
print("Número total de elementos (3*2*4*5): ", tf.size(rank_4_tensor_zeros_tf).numpy())

Tipo de cada elemento: <dtype: 'float32'>
Número de ejes: 4
Forma del tensor: (3, 2, 4, 5)
Elementos en el eje 0 del tensor: 3
Elementos en el último eje del tensor: 5
Número total de elementos (3*2*4*5):  120


In [ ]:
# PyTorch
print("Tipo de cada elemento:", rank_4_tensor_ones_pt.dtype)
print("Número de ejes:", rank_4_tensor_ones_pt.ndim)
print("Forma del tensor:", rank_4_tensor_ones_pt.shape)
print("Elementos en el eje 0 del tensor:", rank_4_tensor_ones_pt.shape[0])
print("Elementos en el último eje del tensor:", rank_4_tensor_ones_pt.shape[-1])
print("Número total de elementos (3*2*4*5): ", rank_4_tensor_ones_pt.numel())

Tipo de cada elemento: torch.float32
Número de ejes: 4
Forma del tensor: torch.Size([3, 2, 4, 5])
Elementos en el eje 0 del tensor: 3
Elementos en el último eje del tensor: 5
Número total de elementos (3*2*4*5):  120


Aunque a menudo nos referimos a los ejes por sus índices, siempre debes tener presente el significado de cada uno. Por lo general, los ejes se ordenan de lo global a lo local: primero el eje del lote (*batch*), seguido de las dimensiones espaciales, y por último las características (*features*) para cada ubicación. De esta manera, los vectores de características se almacenan en regiones contiguas de la memoria.

<table>
<tr>
<th>Tipico orden de las dimensiones</th>
</tr>
<tr>
    <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/shape2.png?raw=1" alt="Keep track of what each axis is. A 4-axis tensor might be: Batch, Width, Height, Features">
  </td>
</tr>
</table>

### Operaciones con Tensores

Tanto PyTorch como TensorFlow ofrecen una extensa biblioteca con más de 100 operaciones para tensores. Estas incluyen transposición, indexación, segmentación (*slicing*), operaciones matemáticas, álgebra lineal, muestreo aleatorio y muchas más.

La gran ventaja de estas estructuras es que cada una de estas operaciones puede ejecutarse en una GPU (típicamente a velocidades mucho mayores que en una CPU). Si estás utilizando Google Colab para seguir este *notebook*, puedes asignar una GPU yendo al menú **Entorno de ejecución > Cambiar tipo de entorno de ejecución** (o *Runtime > Change runtime type*) y seleccionando **GPU**.

In [ ]:
# tensorflow
a = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])
b = tf.ones([2, 2])

# pytorch
c = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0]])
d = torch.ones(size=[2,2])

In [ ]:
print("=== TENSORFLOW ===")
# Suma elemento a elemento
print("Suma (TF):")
print(tf.add(a, b), "\n")

# Multiplicación elemento a elemento (element-wise)
print("Multiplicación elemento a elemento (TF):")
print(tf.multiply(a, b), "\n")

# Multiplicación matricial (álgebra lineal)
print("Multiplicación matricial (TF):")
print(tf.matmul(a, b), "\n")

print("=== PYTORCH ===")
# Suma elemento a elemento
print("Suma (PyTorch):")
print(torch.add(c, d), "\n")

# Multiplicación elemento a elemento (element-wise)
print("Multiplicación elemento a elemento (PyTorch):")
print(torch.multiply(c, d), "\n") # También se puede usar torch.mul(a, b)

# Multiplicación matricial (álgebra lineal)
print("Multiplicación matricial (PyTorch):")
print(torch.matmul(c, d), "\n")

=== TENSORFLOW ===
Suma (TF):
tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32) 

Multiplicación elemento a elemento (TF):
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32) 

Multiplicación matricial (TF):
tf.Tensor(
[[3. 3.]
 [7. 7.]], shape=(2, 2), dtype=float32) 

=== PYTORCH ===
Suma (PyTorch):
tensor([[2., 3.],
        [4., 5.]]) 

Multiplicación elemento a elemento (PyTorch):
tensor([[1., 2.],
        [3., 4.]]) 

Multiplicación matricial (PyTorch):
tensor([[3., 3.],
        [7., 7.]]) 



In [ ]:
print("=== TENSORFLOW (Usando Operadores) ===")
print("Suma elemento a elemento (a + b):")
print(a + b, "\n")

print("Multiplicación elemento a elemento (a * b):")
print(a * b, "\n")

print("Multiplicación matricial / producto punto (a @ b):")
print(a @ b, "\n")


print("=== PYTORCH (Usando Operadores) ===")
print("Suma elemento a elemento (c + d):")
print(c + d, "\n")

print("Multiplicación elemento a elemento (c * d):")
print(c * d, "\n")

print("Multiplicación matricial / producto punto (c @ d):")
print(c @ d, "\n")

=== TENSORFLOW (Usando Operadores) ===
Suma elemento a elemento (a + b):
tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32) 

Multiplicación elemento a elemento (a * b):
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32) 

Multiplicación matricial / producto punto (a @ b):
tf.Tensor(
[[3. 3.]
 [7. 7.]], shape=(2, 2), dtype=float32) 

=== PYTORCH (Usando Operadores) ===
Suma elemento a elemento (c + d):
tensor([[2., 3.],
        [4., 5.]]) 

Multiplicación elemento a elemento (c * d):
tensor([[1., 2.],
        [3., 4.]]) 

Multiplicación matricial / producto punto (c @ d):
tensor([[3., 3.],
        [7., 7.]]) 



### Operaciones de Reducción y Funciones Comunes

Las operaciones de reducción combinan o procesan los elementos de un tensor para devolver un resumen estadístico (como el valor máximo, la suma o el promedio).

A diferencia de las funciones estándar de Python (`max()`, `sum()`), las funciones nativas de los frameworks (`reduce_max`, `argmax`, etc.) están optimizadas para ejecutarse en paralelo en la GPU.

* **`reduce_max` / `max`**: Devuelve el valor máximo dentro del tensor.
* **`argmax`**: Devuelve la posición (índice) donde se encuentra el valor máximo.
* **`softmax`**: Aplica la función Softmax, convirtiendo los valores (llamados *logits*) en una distribución de probabilidades que suman 1.

In [ ]:
print("=== TENSORFLOW ===")
c_tf = tf.constant([[4.0, 5.0],
                    [10.0, 1.0]])

# Encontrar el valor más grande de todo el tensor
print("Valor máximo (TF):", tf.reduce_max(c_tf))

# Encontrar el índice del valor más grande (por defecto aplana el tensor o actúa a lo largo de un eje)
print("Índice del valor máximo (TF):", tf.math.argmax(c_tf))

# Calcular la función Softmax a lo largo del último eje
print("Softmax (TF):\n", tf.nn.softmax(c_tf), "\n")


print("=== PYTORCH ===")
c_pt = torch.tensor([[4.0, 5.0],
                     [10.0, 1.0]])

# Encontrar el valor más grande de todo el tensor
print("Valor máximo (PyTorch):", torch.max(c_pt))

# Encontrar el índice del valor más grande de todo el tensor
print("Índice del valor máximo (PyTorch):", torch.argmax(c_pt))

# Calcular la función Softmax (en PyTorch es obligatorio especificar el eje o dim)
print("Softmax (PyTorch):\n", torch.softmax(c_pt, dim=-1))

=== TENSORFLOW ===
Valor máximo (TF): tf.Tensor(10.0, shape=(), dtype=float32)
Índice del valor máximo (TF): tf.Tensor([1 0], shape=(2,), dtype=int64)
Softmax (TF):
 tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32) 

=== PYTORCH ===
Valor máximo (PyTorch): tensor(10.)
Índice del valor máximo (PyTorch): tensor(2)
Softmax (PyTorch):
 tensor([[2.6894e-01, 7.3106e-01],
        [9.9988e-01, 1.2339e-04]])


## Indexación

### Indexación en un solo eje (*Single-axis indexing*)

Tanto **PyTorch** como **TensorFlow** siguen las reglas estándar de indexación de Python —similares a la [indexación de una lista o cadena de texto en Python](https://docs.python.org/3/tutorial/introduction.html#strings)— así como las convenciones básicas de indexación de NumPy:

* Los índices comienzan en `0`.
* Los índices negativos cuentan hacia atrás, desde el final hacia el principio.
* Se utilizan dos puntos `:` para extraer segmentos (*slices*): `inicio:fin:paso`.


In [ ]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


La indexación con un escalar elimina el eje:

In [ ]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 2.0
Second: 3.0
Last: 4.0


La indexación con un segmento `:` (*slice*) mantiene el eje:

In [ ]:
print("Todo:", rank_1_tensor[:].numpy())
print("Antes del 4:", rank_1_tensor[:4].numpy())
print("Desde el 4 hasta el final:", rank_1_tensor[4:].numpy())
print("Desde el 2, antes del 7:", rank_1_tensor[2:7].numpy())
print("Un elemento sí y otro no (paso de 2):", rank_1_tensor[::2].numpy())
print("Invertido:", rank_1_tensor[::-1].numpy())

Todo: [ 0  1  1  2  3  5  8 13 21 34]
Antes del 4: [0 1 1 2]
Desde el 4 hasta el final: [ 3  5  8 13 21 34]
Desde el 2, antes del 7: [1 2 3 5 8]
Un elemento sí y otro no (paso de 2): [ 0  1  3  8 21]
Invertido: [34 21 13  8  5  3  2  1  1  0]


### Indexación en tensores de rango superior (Multi-axis indexing)

Los tensores de rango superior (matrices o tensores multidimensionales) se indexan pasando múltiples índices separados por comas.

Las mismísimas reglas aplicadas en el caso de un solo eje se aplican a cada eje de forma independiente tanto en **PyTorch** como en **TensorFlow**.

Al pasar un número entero para cada índice, el resultado es un escalar.


In [ ]:
# pytorch
rank_2_tensor = torch.tensor([[1, 2],
                              [3, 4],
                              [5, 6]], dtype=torch.float16)
print(rank_2_tensor[1, 1].numpy())

4.0


You can index using any combination of integers and slices:

In [ ]:
# Obtener tensores de filas y columnas
print("Segunda fila:", rank_2_tensor[1, :].numpy())
print("Segunda columna:", rank_2_tensor[:, 1].numpy())
print("Última fila:", rank_2_tensor[-1, :].numpy())
print("Primer elemento en la última columna:", rank_2_tensor[0, -1].numpy())
print("Omitir la primera fila:")
print(rank_2_tensor[1:, :].numpy(), "\n")

Segunda fila: [3. 4.]
Segunda columna: [2. 4. 6.]
Última fila: [5. 6.]
Primer elemento en la última columna: 2.0
Omitir la primera fila:
[[3. 4.]
 [5. 6.]] 



Ejercicio con un tensor de 3 ejes?

<table>
<tr>
<th colspan=2>Selección de la última característica (feature) a través de todas las ubicaciones en cada ejemplo del lote (batch) </th>
</tr>
<tr>
    <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/index1.png?raw=1" alt="A 3x2x5 tensor with all the values at the index-4 of the last axis selected.">
  </td>
      <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/index2.png?raw=1" alt="The selected values packed into a 2-axis tensor.">
  </td>
</tr>
</table>

In [ ]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor[:,:,4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


## Manipulación de Formas (*Manipulating Shapes*)

Cambiar la forma (*reshape*) de un tensor es una herramienta de gran utilidad en el aprendizaje profundo. Permite reestructurar las dimensiones de un tensor hacia una nueva forma sin alterar sus datos.

Las operaciones de cambio de forma —como `tf.reshape` en TensorFlow o `torch.reshape` / `.view()` en PyTorch— son extremadamente rápidas y eficientes en términos de memoria (operaciones de bajo costo), ya que **no duplican los datos subyacentes en la memoria RAM/VRAM**, sino que simplemente crean una nueva "vista" o interpretación de cómo se leen esos mismos datos.


In [ ]:
# Creamos un tensor unidimensional inicial con 3 elementos (ej. vector de 1x3)
x_tf = tf.constant([1.0, 2.0, 3.0])
x_pt = torch.tensor([1.0, 2.0, 3.0])

print("=== TENSORFLOW ===")
# Puedes cambiar la forma de un tensor a una nueva dimensión.
# Nota que le pasas una lista o tupla con la nueva forma deseada [filas, columnas].
# Aquí transformamos un vector de 3 elementos a una matriz de 1 fila y 3 columnas (1x3).
reshaped_tf = tf.reshape(x_tf, [1, 3])

print("Tensor original", x_tf.numpy())
print("Forma original (TF):", x_tf.shape)
print("Nueva forma (TF):", reshaped_tf.shape)
print("Contenido (TF):\n", reshaped_tf.numpy(), "\n")

print("=== PYTORCH ===")
# En PyTorch puedes usar torch.reshape() o el método equivalente .view()
# Pasamos la nueva forma [1, 3] como lista o tupla.
reshaped_pt = torch.reshape(x_pt, [1, 3])
# Alternativa muy común en PyTorch: reshaped_pt = x_pt.view(1, 3)

print("Forma original (PyTorch):", x_pt.shape)
print("Nueva forma (PyTorch):", reshaped_pt.shape)
print("Contenido (PyTorch):\n", reshaped_pt.numpy())

=== TENSORFLOW ===
Tensor original [1. 2. 3.]
Forma original (TF): (3,)
Nueva forma (TF): (1, 3)
Contenido (TF):
 [[1. 2. 3.]] 

=== PYTORCH ===
Forma original (PyTorch): torch.Size([3])
Nueva forma (PyTorch): torch.Size([1, 3])
Contenido (PyTorch):
 [[1. 2. 3.]]


Los datos mantienen su distribución en memoria y se crea un nuevo tensor con la forma solicitada que apunta a los mismos datos subyacentes. Tanto **TensorFlow** como **PyTorch** utilizan por defecto el orden de memoria "row-major" (estilo C), donde al incrementar el índice situado más a la derecha se avanza una única posición contigua en memoria.

Por lo general, el único uso razonable de `reshape` (ya sea `tf.reshape` o `torch.reshape`) es combinar o dividir ejes adyacentes (o añadir/eliminar dimensiones de tamaño 1).

Para este tensor de forma `3x2x5`, reestructurarlo a `(3x2)x5` [es decir, `6x5`] o a `3x(2x5)` [es decir, `3x10`] son opciones totalmente válidas y razonables, ya que los segmentos de datos (*slices*) no se mezclan entre sí.

In [ ]:
print(tf.reshape(rank_3_tensor, [3*2, 5]), "\n")
print(tf.reshape(rank_3_tensor, [3, -1]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


<table>
<th colspan=3>
Algunos buenos reshapes.
</th>
<tr>
  <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/reshape-before.png?raw=1" alt="A 3x2x5 tensor">
  </td>
  <td>
  <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/reshape-good1.png?raw=1" alt="The same data reshaped to (3x2)x5">
  </td>
  <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/reshape-good2.png?raw=1" alt="The same data reshaped to 3x(2x5)">
  </td>
</tr>
</table>


### La regla de oro del cambio de forma (*Reshaping*)

El cambio de forma (*reshape*) "funcionará" técnicamente para cualquier nueva estructura que mantenga la misma cantidad total de elementos, **pero no servirá de nada útil si no respetas el orden de los ejes**.

Intercambiar o reordenar los ejes usando `reshape` (como `tf.reshape` o `torch.reshape`) **no funciona**; para cambiar el orden de los ejes debes usar funciones de transposición, como **`tf.transpose`** en TensorFlow o **`torch.permute` / `.T`** en PyTorch.


In [ ]:
# Ejemplos incorrectos: no hagas esto

# No puedes reordenar ejes con reshape.
print(tf.reshape(rank_3_tensor, [2, 3, 5]), "\n")

# Esto es un desastre
print(tf.reshape(rank_3_tensor, [5, 6]), "\n")

# Esto no funciona en absoluto
try:
    tf.reshape(rank_3_tensor, [7, -1])
except Exception as e:
    print(f"{type(e).__name__}: {e}")

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32) 

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]


<table>
<th colspan=3>
Mal uso del reshape.
</th>
<tr>
  <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/reshape-bad.png?raw=1" alt="You can't reorder axes, use tf.transpose for that">
  </td>
  <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/reshape-bad4.png?raw=1" alt="Anything that mixes the slices of data together is probably wrong.">
  </td>
  <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/reshape-bad2.png?raw=1" alt="The new shape must fit exactly.">
  </td>
</tr>
</table>

## Más sobre los tipos de datos (*DTypes*)

Para inspeccionar el tipo de dato de un tensor, tanto en **TensorFlow** como en **PyTorch**, se utiliza la propiedad `.dtype`.

Al crear un tensor a partir de un objeto de Python (como una lista o una tupla), puedes especificar el tipo de dato de forma opcional mediante el argumento `dtype`.

Si no lo especificas explícitamente, ambos frameworks eligen automáticamente un tipo de dato capaz de representar tu información:
* Convertir enteros de Python a números enteros de 32 bits (`tf.int32` / `torch.int64`*).
* Convertir números de coma flotante de Python a flotantes de 32 bits (`tf.float32` / `torch.float32`).

Por lo demás, utilizan reglas equivalentes a las de **NumPy** para determinar el tipo al convertir arreglos.

Finalmente, es posible cambiar explícitamente de un tipo de dato a otro (*casting*).

In [ ]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
# Ahora, convierte a uint8 y pierde la precisión decimal
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


## Broadcasting

El concepto de *Broadcasting* (o difusión) es una característica tomada directamente de [NumPy](https://numpy.org/doc/stable/user/basics.broadcasting.html). En pocas palabras, bajo ciertas condiciones, los tensores más pequeños se "estiran" o expanden automáticamente para igualar la forma (*shape*) de los tensores más grandes al realizar operaciones combinadas entre ellos.

El caso más simple y habitual ocurre al multiplicar o sumar un escalar a un tensor. En este escenario, el escalar se difunde a lo largo de todas las dimensiones para adquirir la misma forma que el otro tensor.

In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant(2)
z = tf.constant([2, 2, 2])
# Todos son el mismo cálculo
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


De la misma manera, los ejes de longitud 1 pueden estirarse para igualar los demás argumentos. Ambos argumentos pueden estirarse simultáneamente en la misma operación.

En este caso, una matriz de `3x1` se multiplica elemento por elemento (*element-wise*) por una matriz de `1x4` para producir una matriz de `3x4`. Observa que el `1` inicial es opcional: la forma (*shape*) de `y` puede ser simplemente `[4]`.

In [ ]:
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


<table>
<tr>
  <th>El vector <code>[3, 1]</code> por <code>[1, 4]</code> resulta <code>[3,4]</code> </th>
</tr>
<tr>
  <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/broadcasting.png?raw=1" alt="Adding a 3x1 matrix to a 4x1 matrix results in a 3x4 matrix">
  </td>
</tr>
</table>


## Tensores Irregulares (*Ragged Tensors*)

Un tensor que posee un número variable de elementos a lo largo de algún eje se denomina "irregular" (*ragged*). Se utiliza `tf.ragged.RaggedTensor` en TensorFlow o listas de tensores / estructuras especializadas como `nested_tensor` (o empaquetado con relleno/*padding*) en PyTorch para trabajar con datos irregulares.

Por ejemplo, la siguiente estructura no se puede representar directamente como un tensor denso o regular tradicional (ya que las filas tienen diferentes longitudes):

<table>
<tr>
  <th>Un `tf.RaggedTensor`, shape: <code>[4, None]</code></th>
</tr>
<tr>
  <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/ragged.png?raw=1" alt="A 2-axis ragged tensor, each row can have a different length.">
  </td>
</tr>
</table>

In [ ]:
# tensorflow
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

ragged_tensor_tf = tf.ragged.constant(ragged_list)
print(ragged_tensor)

nested_tensor([
  tensor([0, 1, 2, 3]),
  tensor([4, 5]),
  tensor([6, 7, 8]),
  tensor([9])
])


In [ ]:
# pytorch
ragged_tensor = torch.nested.nested_tensor([torch.tensor(row) for row in ragged_list])
print(ragged_tensor)

nested_tensor([
  tensor([0, 1, 2, 3]),
  tensor([4, 5]),
  tensor([6, 7, 8]),
  tensor([9])
])


La forma (*shape*) de un `tf.RaggedTensor` contendrá algunos ejes con longitudes desconocidas:

In [ ]:
print(ragged_tensor_tf.shape)

(4, None)


## Tensores Esparsos (*Sparse Tensors*)

En ocasiones, los datos son dispersos o esparsos (*sparse*), como en el caso de un espacio de incrustación (*embedding*) de gran dimensión o matrices con una gran cantidad de ceros. Tanto **TensorFlow** (`tf.sparse.SparseTensor`) como **PyTorch** (`torch.sparse_coo_tensor`) ofrecen soporte nativo y operaciones optimizadas para almacenar y procesar datos esparsos de manera eficiente sin desperdiciar memoria RAM/VRAM en ceros.

<table>
<tr>
  <th>Un `tf.SparseTensor`, shape: <code>[3, 4]</code></th>
</tr>
<tr>
  <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/sparse.png?raw=1" alt="An 3x4 grid, with values in only two of the cells.">
  </td>
</tr>
</table>

In [ ]:
# tensorflow
# Los tensores esparsos almacenan valores por índice de forma eficiente en memoria
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# Puedes convertir tensores esparsos a densos
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [ ]:
# pytorch
# Nota: En PyTorch los índices se pasan como un tensor de forma [dimensiones, num_elementos]
indices = torch.tensor([[0, 1],
                        [0, 2]])
values = torch.tensor([1, 2])
dense_shape = (3, 4)

sparse_tensor = torch.sparse_coo_tensor(indices, values, size=dense_shape)
print(sparse_tensor, "\n")

# Puedes convertir tensores esparsos a densos
print(sparse_tensor.to_dense())

tensor(indices=tensor([[0, 1],
                       [0, 2]]),
       values=tensor([1, 2]),
       size=(3, 4), nnz=2, layout=torch.sparse_coo) 

tensor([[1, 0, 0, 0],
        [0, 0, 2, 0],
        [0, 0, 0, 0]])


/tmp/ipykernel_427/2700516402.py:8: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  sparse_tensor = torch.sparse_coo_tensor(indices, values, size=dense_shape)


Estudio más profundo en pytorch: https://docs.pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html

Álgebra Lineal: https://www.d2l.ai/chapter_preliminaries/linear-algebra.html

Geometría y operaciones algebraicas: https://en.d2l.ai/chapter_appendix-mathematics-for-deep-learning/geometry-linear-algebraic-ops.html

Descomposiciones en eigenvectores: https://www.d2l.ai/chapter_appendix-mathematics-for-deep-learning/eigendecomposition.html